import React from "react";
import { 
  Store, 
  ShoppingBag, 
  Bus, 
  Receipt, 
  Smartphone, 
  Pill, 
  TrendingUp, 
  Home, 
  HandCoins, 
  Users, 
  Layers,
  ArrowUpRight,
  Dumbbell,
  Coffee,
  Gift,
  Dog,
  Book,
  Music,
  Camera,
  Gamepad2,
  Scissors,
  Plane,
  CreditCard,
  Banknote,
  Sparkles,
  Undo,
  Heart,
  Car,
  Utensils
} from "lucide-react-native";
import { Transaction, Bill } from "../types";

export const MOCK_TRANSACTIONS: Transaction[] = [
  { 
    id: "1", 
    amount: 1571, 
    description: "Amazon Shopping", 
    category: "Shopping", 
    date: "2026-04-05T10:30:00Z", 
    type: "expense", 
    paymentMethod: "upi",
    isSpend: true,
    smsContent: "Dear UPI user A/C X8361 debited by 1571.00 on date 05Apr26 trf to AMAZON Refno 609619438605 If not u? call-1800111109"
  },
  { id: "2", amount: 120000, description: "Monthly Salary", category: "Income", date: "2026-04-01T09:00:00Z", type: "income", paymentMethod: "bank", isSpend: false },
  { 
    id: "3", 
    amount: 43364.88, 
    description: "FINZOOM INVESTME", 
    category: "Investments", 
    date: "2026-04-06T08:40:00Z", 
    type: "expense", 
    paymentMethod: "upi",
    isSpend: true,
    smsContent: "Dear UPI user A/C X8361 debited by 43364.88 on date 06Apr26 trf to FINZOOM INVESTME Refno 609619438605 If not u? call-1800111109 for other services-18001234-SBI"
  },
  { id: "4", amount: 2838, description: "Misc Expenses", category: "Miscellaneous", date: "2026-04-03T14:20:00Z", type: "expense", paymentMethod: "cash", isSpend: true },
  { id: "5", amount: 1031, description: "Pharmacy", category: "Medical", date: "2026-04-02T08:00:00Z", type: "expense", paymentMethod: "upi", isSpend: true },
  { id: "6", amount: 234, description: "Grocery Store", category: "Grocery", date: "2026-04-04T12:00:00Z", type: "expense", paymentMethod: "upi", isSpend: true },
  { id: "7", amount: 87, description: "Credit Card Interest", category: "Bills/Utilities", date: "2026-04-05T18:00:00Z", type: "expense", paymentMethod: "bank", isSpend: true },
  { id: "8", amount: 3500, description: "Dinner with friends", category: "Dining", date: "2026-03-15T20:00:00Z", type: "expense", paymentMethod: "upi", isSpend: true },
  { id: "9", amount: 1200, description: "Movie tickets", category: "Entertainment", date: "2026-03-20T18:00:00Z", type: "expense", paymentMethod: "upi", isSpend: true },
];

export const MOCK_BILLS: Bill[] = [
  { id: "1", amount: 850, description: "Electricity Bill", dueDate: "2026-04-10", isPaid: false },
  { id: "2", amount: 450, description: "Internet Bill", dueDate: "2026-04-15", isPaid: false },
];

export const CATEGORY_COLORS: Record<string, string> = {
  "Dining": "#4ADE80",
  "Grocery": "#22C55E",
  "Shopping": "#EC4899",
  "Transport": "#F97316",
  "Bills/Utilities": "#EAB308",
  "Entertainment": "#D946EF",
  "Medical": "#EF4444",
  "Investments": "#8B5CF6",
  "Rent/Mortgage": "#10B981",
  "Loan": "#3B82F6",
  "Beauty/Fitness": "#F472B6",
  "Maid/Driver": "#64748B",
  "Education": "#FACC15",
  "Miscellaneous": "#94A3B8",
  "Income": "#22C55E",
  "Travel": "#0EA5E9",
  "Subscriptions": "#6366F1",
  "Gifts": "#F43F5E",
  "Pets": "#D97706",
  "Books": "#8B5CF6",
  "Music": "#EC4899",
  "Camera": "#64748B",
  "Gaming": "#F59E0B",
  "Salary": "#10B981",
  "Bonus": "#FACC15",
  "Refund": "#14B8A6",
  "UPI": "#7ED9D9",
};

export const CATEGORY_ICONS: Record<string, React.ElementType> = {
  "Dining": Utensils,
  "Grocery": ShoppingBag,
  "Shopping": ShoppingBag,
  "Transport": Car,
  "Bills/Utilities": Receipt,
  "Entertainment": Smartphone,
  "Medical": Heart,
  "Investments": TrendingUp,
  "Rent/Mortgage": Home,
  "Loan": HandCoins,
  "Beauty/Fitness": Scissors,
  "Maid/Driver": Users,
  "Education": Book,
  "Miscellaneous": Layers,
  "Income": Banknote,
  "Travel": Plane,
  "Subscriptions": CreditCard,
  "Gifts": Gift,
  "Pets": Dog,
  "Books": Book,
  "Music": Music,
  "Camera": Camera,
  "Gaming": Gamepad2,
  "Salary": Banknote,
  "Bonus": Sparkles,
  "Refund": Undo,
  "UPI": Smartphone,
};

export const INITIAL_CATEGORIES = [
  { id: 'dining', label: 'Dining', icon: Utensils, color: CATEGORY_COLORS["Dining"] },
  { id: 'grocery', label: 'Grocery', icon: ShoppingBag, color: CATEGORY_COLORS["Grocery"] },
  { id: 'shopping', label: 'Shopping', icon: ShoppingBag, color: CATEGORY_COLORS["Shopping"] },
  { id: 'transport', label: 'Transport', icon: Car, color: CATEGORY_COLORS["Transport"] },
  { id: 'bills', label: 'Bills/Utilities', icon: Receipt, color: CATEGORY_COLORS["Bills/Utilities"] },
  { id: 'entertainment', label: 'Entertainment', icon: Smartphone, color: CATEGORY_COLORS["Entertainment"] },
  { id: 'medical', label: 'Medical', icon: Heart, color: CATEGORY_COLORS["Medical"] },
  { id: 'investments', label: 'Investments', icon: TrendingUp, color: CATEGORY_COLORS["Investments"] },
  { id: 'rent', label: 'Rent/Mortgage', icon: Home, color: CATEGORY_COLORS["Rent/Mortgage"] },
  { id: 'loan', label: 'Loan', icon: HandCoins, color: CATEGORY_COLORS["Loan"] },
  { id: 'beauty', label: 'Beauty/Fitness', icon: Scissors, color: CATEGORY_COLORS["Beauty/Fitness"] },
  { id: 'maid', label: 'Maid/Driver', icon: Users, color: CATEGORY_COLORS["Maid/Driver"] },
  { id: 'education', label: 'Education', icon: Book, color: CATEGORY_COLORS["Education"] },
  { id: 'travel', label: 'Travel', icon: Plane, color: CATEGORY_COLORS["Travel"] },
  { id: 'subscriptions', label: 'Subscriptions', icon: CreditCard, color: CATEGORY_COLORS["Subscriptions"] },
  { id: 'gifts', label: 'Gifts', icon: Gift, color: CATEGORY_COLORS["Gifts"] },
  { id: 'pets', label: 'Pets', icon: Dog, color: CATEGORY_COLORS["Pets"] },
  { id: 'misc', label: 'Miscellaneous', icon: Layers, color: CATEGORY_COLORS["Miscellaneous"] },
];

export const AVAILABLE_ICONS = [
  { name: "Gym", icon: Dumbbell },
  { name: "Coffee", icon: Coffee },
  { name: "Gift", icon: Gift },
  { name: "Pet", icon: Dog },
  { name: "Book", icon: Book },
  { name: "Music", icon: Music },
  { name: "Camera", icon: Camera },
  { name: "Game", icon: Gamepad2 },
];
